## ya que este archivo puede contener informacion sensible, se debe agregar .gitignore
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
stringData:
  mongo-url: 'mongodb://mongo-srv/habits'
